import Head from "next/head";
import * as React from "react";

import { Button, IconButton, Typography } from "@mui/material";
import {
  AddCircleOutlineRounded,
  AddRounded,
  ArrowBackIosNewRounded,
  CheckRounded,
  DeleteOutlineRounded,
  MopedRounded,
  RemoveCircleOutlineRounded,
} from "@mui/icons-material";

import TapsProps from "@/components/Tabs";
import router from "next/router";

export default function Cart() {
  const [openSuccess, SetOpenSuccess] = React.useState(false);

  return (
    <>
      <Head>
        <title>Yaakz Member</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="toolbar">
        <IconButton onClick={() => router.back()}>
          <ArrowBackIosNewRounded />
        </IconButton>
        <Typography style={{ fontSize: 24, marginRight: 50 }}>
          ตะกร้า
        </Typography>
      </div>

      <div className="box-search-item2">
        <div className="box-item">
          <div className="img-item">
            <Typography>รูปภาพ</Typography>
          </div>
          <div style={{ width: 270, marginTop: -5 }}>
            <Typography style={{ height: 55 }}>
              ยอดนักสืบจิ๋ว โคนัน ล.5 - วันสบายๆของซีโร่ (90)
            </Typography>
            <div>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                }}
              >
                <div style={{ display: "flex", justifyContent: "center" }}>
                  <MopedRounded />
                  <Typography style={{ fontSize: 14 }}>
                    พร้อมจัดส่ง 19/12/24
                  </Typography>
                </div>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                  }}
                >
                  <IconButton style={{ width: 30, height: 17 }}>
                    <DeleteOutlineRounded />
                  </IconButton>
                  <IconButton style={{ width: 30, height: 17 }}>
                    <RemoveCircleOutlineRounded />
                  </IconButton>
                  <div
                    style={{
                      backgroundColor: "#D9D9D9",
                      width: 25,
                      height: 25,
                      borderRadius: 5,
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                    }}
                  >
                    <Typography style={{ textAlign: "center" }}>1</Typography>
                  </div>
                  <IconButton style={{ width: 30, height: 17 }}>
                    <AddCircleOutlineRounded />
                  </IconButton>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="box-item">
          <div className="img-item">
            <Typography>รูปภาพ</Typography>
          </div>
          <div style={{ width: 270, marginTop: -5 }}>
            <Typography style={{ height: 55 }}>
              ยอดนักสืบจิ๋ว โคนัน ล.5 - วันสบายๆของซีโร่ (90)
            </Typography>
            <div>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                }}
              >
                <div style={{ display: "flex", justifyContent: "center" }}>
                  <MopedRounded />
                  <Typography style={{ fontSize: 14 }}>
                    พร้อมจัดส่ง 19/12/24
                  </Typography>
                </div>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                  }}
                >
                  <IconButton style={{ width: 30, height: 17 }}>
                    <DeleteOutlineRounded />
                  </IconButton>
                  <IconButton style={{ width: 30, height: 17 }}>
                    <RemoveCircleOutlineRounded />
                  </IconButton>
                  <div
                    style={{
                      backgroundColor: "#D9D9D9",
                      width: 25,
                      height: 25,
                      borderRadius: 5,
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                    }}
                  >
                    <Typography style={{ textAlign: "center" }}>1</Typography>
                  </div>
                  <IconButton style={{ width: 30, height: 17 }}>
                    <AddCircleOutlineRounded />
                  </IconButton>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="box-item">
          <div className="img-item">
            <Typography>รูปภาพ</Typography>
          </div>
          <div style={{ width: 270, marginTop: -5 }}>
            <Typography style={{ height: 55 }}>
              ยอดนักสืบจิ๋ว โคนัน ล.5 - วันสบายๆของซีโร่ (90)
            </Typography>
            <div>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                }}
              >
                <div style={{ display: "flex", justifyContent: "center" }}>
                  <MopedRounded />
                  <Typography style={{ fontSize: 14 }}>
                    พร้อมจัดส่ง 19/12/24
                  </Typography>
                </div>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                  }}
                >
                  <IconButton style={{ width: 30, height: 17 }}>
                    <DeleteOutlineRounded />
                  </IconButton>
                  <IconButton style={{ width: 30, height: 17 }}>
                    <RemoveCircleOutlineRounded />
                  </IconButton>
                  <div
                    style={{
                      backgroundColor: "#D9D9D9",
                      width: 25,
                      height: 25,
                      borderRadius: 5,
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                    }}
                  >
                    <Typography style={{ textAlign: "center" }}>1</Typography>
                  </div>
                  <IconButton style={{ width: 30, height: 17 }}>
                    <AddCircleOutlineRounded />
                  </IconButton>
                </div>
              </div>
            </div>
          </div>
        </div>
        <a href="/check_out">
          <div
            style={{
              justifyContent: "center",
              display: "flex",
              marginTop: 20,
            }}
          >
            <Button className="btn-regis" variant="contained">
              ดำเนินการต่อ
            </Button>
          </div>
        </a>
      </div>

      <TapsProps />
    </>
  );
}
