import Head from "next/head";
import * as React from "react";

import { Box, Button, IconButton, Typography } from "@mui/material";
import {
  ArrowBackIosNewRounded,
  CheckCircleOutlined,
  ModeEditOutlineRounded,
  MopedRounded,
} from "@mui/icons-material";

import TapsProps from "@/components/Tabs";
import DialogProps from "@/components/dialog/DialogSuccess";
import router from "next/router";
import DialogEditUserProps from "@/components/dialog/DialogEditUser";
import { customer_update_seed } from "@/models/seed";
import { AddressOption } from "@/services/StoreUtils";
import { api } from "@/services/AxiosUtils";
import toast from "react-hot-toast";
import dayjs, { locale } from "dayjs";
import { thaiAddress } from "@/models/constants/thaiAddress";

export default function Cart() {
  const [openSuccess, setOpenSuccess] = React.useState(false);
  const [openEditUser, setOpenEditUser] = React.useState(false);
  const [selectedCustomer, setSelectedCustomer] =
    React.useState<EditUser>(customer_update_seed);
  const [address, setAddress] = React.useState<AddressOption[]>([]);
  const [openUpdateCustomer, setOpenUpdateCustomer] = React.useState(false);
  const handleClose = () => {
    setOpenSuccess(false);
    setOpenEditUser(false);
  };
  const handleChangeEdit = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = event.target;
    setSelectedCustomer((prevState: any) => ({
      ...prevState,
      [name]: value,
    }));
  };

  // [Method] - ดึงข้อมูลที่อยู่
  const getAddress = async () => {
    setAddress(thaiAddress);
  };

  const getCustomer = async () => {
    const res = await api.get(`/customer/list?uid=1051`);
    setSelectedCustomer(res.data.item[0]);
  };

  const onOpenUpdateCustomer = async () => {
    const res = await api.get(`/customer/info/${1051}`);

    if (res.data.status === "Success") {
      console.log(res.data);
      setSelectedCustomer((prev) => ({
        ...prev,
        province: String(res.data.data[0].province),
        district: String(res.data.data[0].district),
        sub_district: res.data.data[0].sub_district,
        zip_code: res.data.data[0].zip_code,
        birth_day: res.data.data[0].birth_day,
        address: res.data.data[0].address,
      }));
    }

    setOpenUpdateCustomer(true);
  };

  //[Mathod] - บันทึกการแก้ไขข้อมูลลูกค้า
  const onSubmitUpdateCustomer = async () => {
    setOpenUpdateCustomer(false);
    delete selectedCustomer.birth_day;

    const res = await api.put(
      `/customer/update/${selectedCustomer.id}`,
      selectedCustomer
    );
    if (res.data.status === "Success") {
      toast.success(res.data.msg);
    } else {
      toast.error(res.data.msg);
    }
    console.log(res.data.msg);
  };

  React.useEffect(() => {
    getCustomer();
    getAddress();
  }, []);

  return (
    <>
      <Head>
        <title>Yaakz Member</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className="container">
        <div className="toolbar">
          <IconButton onClick={() => router.back()}>
            <ArrowBackIosNewRounded />
          </IconButton>
          <Typography style={{ fontSize: "24px", marginRight: 50 }}>
            สั่งซื้อ
          </Typography>
          <div />
        </div>

        <div className="box-chk-item">
          <div className="box-chkout-address" style={{ padding: 15 }}>
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                padding: 2,
              }}
            >
              <Typography>ที่อยู่ในการจัดส่ง</Typography>
              <IconButton onClick={() => setOpenEditUser(true)}>
                <ModeEditOutlineRounded />
              </IconButton>
            </div>
            <Typography>ชื่อ : Pukky</Typography>
            <Typography>เบอร์โทรศัพท์ : 06138908xx</Typography>
            <Typography style={{ width: 300 }}>
              ที่อยู่ : 681/6 เลอชาโต ซ.ลาดพร้าว48 แยก12 แขวงสามเสนนอก
              เขตห้วยขวาง 10310
            </Typography>
          </div>

          <div className="box-item">
            <div className="img-item">
              <Typography>รูปภาพ</Typography>
            </div>
            <div style={{ width: 230, marginTop: -5 }}>
              <Typography style={{ height: 55 }}>
                ยอดนักสืบจิ๋ว โคนัน ล.5 - วันสบายๆของซีโร่ (90)
              </Typography>
              <div>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                  }}
                >
                  <div style={{ display: "flex", justifyContent: "center" }}>
                    <MopedRounded />
                    <Typography style={{ fontSize: 14 }}>
                      พร้อมจัดส่ง 19/12/24
                    </Typography>
                  </div>
                  <div
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                    }}
                  >
                    <Typography>x1</Typography>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="box-item">
            <div className="img-item">
              <Typography>รูปภาพ</Typography>
            </div>
            <div style={{ width: 230, marginTop: -5 }}>
              <Typography style={{ height: 55 }}>
                ยอดนักสืบจิ๋ว โคนัน ล.5 - วันสบายๆของซีโร่ (90)
              </Typography>
              <div>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                  }}
                >
                  <div style={{ display: "flex", justifyContent: "center" }}>
                    <MopedRounded />
                    <Typography style={{ fontSize: 14 }}>
                      พร้อมจัดส่ง 19/12/24
                    </Typography>
                  </div>
                  <div
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                    }}
                  >
                    <Typography>x1</Typography>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="box-item">
            <div className="img-item">
              <Typography>รูปภาพ</Typography>
            </div>
            <div style={{ width: 230, marginTop: -5 }}>
              <Typography style={{ height: 55 }}>
                ยอดนักสืบจิ๋ว โคนัน ล.5 - วันสบายๆของซีโร่ (90)
              </Typography>
              <div>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                  }}
                >
                  <div style={{ display: "flex", justifyContent: "center" }}>
                    <MopedRounded />
                    <Typography style={{ fontSize: 14 }}>
                      พร้อมจัดส่ง 19/12/24
                    </Typography>
                  </div>
                  <div
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                    }}
                  >
                    <Typography>x1</Typography>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <a href="order_list">
            <div className="bottom-btn">
              <Button
                className="btn-regis"
                variant="contained"
                onClick={() => setOpenSuccess(true)}
              >
                ดำเนินการต่อ
              </Button>
            </div>
          </a>
        </div>
        <DialogProps
          open={openSuccess}
          onClose={handleClose}
          text="สั่งซื้อสำเร็จ"
          icon={
            <CheckCircleOutlined
              style={{ width: 100, height: 100, color: "#60D36C" }}
            />
          }
        />
        <DialogEditUserProps
          open={openUpdateCustomer}
          onClose={handleClose}
          customer_name={selectedCustomer.name}
          customer_phone={selectedCustomer.phone}
          customer_email={selectedCustomer.email}
          customer_address={selectedCustomer.address}
          customer_main_address={[
            selectedCustomer.province,
            selectedCustomer.district,
            `${selectedCustomer.sub_district} ${selectedCustomer.zip_code}`,
          ]}
          onChangeCustomerData={handleChangeEdit}
          locale={locale}
          customer_birth_day={selectedCustomer.birth_day}
          onChangeProvince={(e) =>
            setSelectedCustomer({ ...selectedCustomer, province: Number(e) })
          }
          onChangeDistrict={(e) =>
            setSelectedCustomer({ ...selectedCustomer, district: e })
          }
          onChangeSubDistrictAndPostCode={(e, a) =>
            setSelectedCustomer({
              ...selectedCustomer,
              sub_district: e,
              zip_code: a,
            })
          }
          cascaderAddress={address}
          onChangeDate={(value: any) => {
            setSelectedCustomer({
              ...selectedCustomer,
              bod: !value ? null : dayjs(value).format("YYYY-MM-DD"),
            });
          }}
          onSubmit={onSubmitUpdateCustomer}
        />
      </Box>
    </>
  );
}
