import Head from "next/head";
import * as React from "react";

import {
  Box,
  Button,
  Dialog,
  DialogContent,
  DialogTitle,
  IconButton,
  InputBase,
  Typography,
} from "@mui/material";
import {
  AddRounded,
  ArrowForwardIosRounded,
  CardGiftcardRounded,
  CleanHandsRounded,
  ClearRounded,
  MenuBookRounded,
  SearchOffOutlined,
  SearchOutlined,
} from "@mui/icons-material";
import {
  SearchIconWrapper,
  SelectInputBase,
  Search,
} from "@/services/StyleUtils";
import ImageSlider from "../components/ImageSlider";
import TapsProps from "@/components/Tabs";

export default function Home() {
  const [searchPlaceholder, setSearchPlaceholder] =
    React.useState("ค้นหาหนังสือ");

  const [openSearch, setOpenSearch] = React.useState(false);
  const slides = [
    {
      title: "Slide 1",
      description: "Description for Slide 1",
    },
    {
      title: "Slide 2",
      description: "Description for Slide 2",
    },
    {
      title: "Slide 3",
      description: "Description for Slide 3",
    },
    // Add more slides as needed
  ];
  return (
    <>
      <Head>
        <title>Yaakz Member</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="toolbar">
        <div />
        <Typography style={{ fontSize: "24px" }}>หน้าแรก</Typography>

        <IconButton onClick={() => setOpenSearch(true)}>
          <SearchOutlined />
        </IconButton>
      </div>
      <Box className="container">
        {/* <div className="box-search-item">
          <div className="search-item">
            <Search>
              <SearchIconWrapper>
                <SearchOutlined />
              </SearchIconWrapper>
              <a href="/search_product" style={{ cursor: "pointer" }}>
                <InputBase
                  sx={{ marginLeft: 6, marginTop: 0.5 }}
                  placeholder={searchPlaceholder}
                  inputProps={{ "aria-label": "search" }}
                />
              </a>
            </Search>
          </div>
          <div>
          <Button
            className="btn-add-item"
            variant="contained"
            color="secondary"
          >
            <AddRounded />
            <MenuBookRounded />
          </Button>
        </div>
        </div> */}

        <div className="box-points">
          <div className="box-points-left">
            <CardGiftcardRounded sx={{ width: 40, height: 40 }} />
            <div>
              <Typography style={{ fontSize: "12px", marginBottom: 5 }}>
                คะแนนสะสม
              </Typography>
              <div className="point">
                <Typography style={{ fontSize: "20px" }}>200</Typography>
                <div className="icon-point">
                  <div className="icon-point2"></div>
                  <Typography sx={{ mt: -2.6, ml: 0.8, color: "#fff" }}>
                    P
                  </Typography>
                </div>
              </div>
            </div>
          </div>
          <div className="box-points-right">
            <Typography style={{ fontSize: "14px" }}>30คะแนน</Typography>
            <Typography style={{ fontSize: "14px", marginBottom: 5 }}>
              คะแนนหมดอายุ 31 ธ.ค. 67
            </Typography>
            <a href="/rewards">
              <Button
                className="point-detail"
                variant="contained"
                color="secondary"
              >
                <Typography style={{ fontSize: "14px" }}>
                  ดูรายละเอียดเพิ่มเติม
                </Typography>
              </Button>
            </a>
          </div>
        </div>

        <div className="product-index-container">
          <div style={{ marginTop: 40 }}>
            <div
              style={{
                backgroundColor: "#F1F1F1",
                width: "100%",
                height: 50,
                alignItems: "center",
                display: "flex",
              }}
            >
              <Typography style={{ fontSize: "22px", marginLeft: 20 }}>
                โปรโมชั่น
              </Typography>
            </div>
            <div>
              <ImageSlider slides={slides} />
            </div>
          </div>

          <div style={{ marginTop: 40 }}>
            <div
              style={{
                backgroundColor: "#F1F1F1",
                width: "100%",
                height: 50,
                alignItems: "center",
                display: "flex",
                justifyContent: "space-between",
              }}
            >
              <Typography style={{ fontSize: "22px", marginLeft: 20 }}>
                Pre- Order
              </Typography>

              <a href="pre_order">
                <Typography style={{ fontSize: "18px", marginRight: 20 }}>
                  ดูเพิ่มเติม
                </Typography>
              </a>
            </div>
            <div>
              <ImageSlider slides={slides} />
            </div>
          </div>
        </div>

        <Dialog
          open={openSearch}
          PaperProps={{
            style: { borderRadius: 20, height: 500 },
          }}
        >
          <div
            style={{
              justifyContent: "space-between",
              display: "flex",
            }}
          >
            <DialogTitle>ค้นหาหนังสือ</DialogTitle>
            <IconButton style={{ margin: 5 }}>
              <ClearRounded onClick={() => setOpenSearch(false)} />
            </IconButton>
          </div>

          <DialogContent>
            <div style={{ justifyContent: "center", display: "flex" }}>
              <div className="search-input">
                <InputBase
                  placeholder="กรอกชื่อหนังสือ"
                  sx={{ marginLeft: 1, marginTop: 0.5 }}
                  inputProps={{ "aria-label": "search" }}
                />
              </div>
              <IconButton onClick={() => setOpenSearch(true)}>
                <SearchOutlined />
              </IconButton>
            </div>
            <a href="search_product">
              <div className="box-search-item3">
                <Typography style={{ padding: 10, width: 250 }}>
                  โคนันภาค 1
                </Typography>
                <ArrowForwardIosRounded
                  style={{ width: 16, height: 16, marginTop: 10, padding: 5 }}
                />
              </div>
            </a>
            <a href="search_product">
              <div className="box-search-item3">
                <Typography style={{ padding: 10, width: 250 }}>
                  โคนันภาค 1
                </Typography>
                <ArrowForwardIosRounded
                  style={{ width: 16, height: 16, marginTop: 10, padding: 5 }}
                />
              </div>
            </a>
          </DialogContent>
        </Dialog>
      </Box>

      <TapsProps />
    </>
  );
}
