import Head from "next/head";
import * as React from "react";
import Image from "next/image";
import mypic from "../assets/imges/Yaakz_Profile-1000-01_(1)-transformed.png";
import {
  Box,
  Button,
  Divider,
  IconButton,
  InputAdornment,
  InputBase,
  TextField,
  Typography,
} from "@mui/material";
import {
  AddRounded,
  ErrorOutlineRounded,
  Search,
  SearchOutlined,
  Visibility,
  VisibilityOff,
} from "@mui/icons-material";
import { SearchIconWrapper } from "@/services/StyleUtils";
import DialogProps from "@/components/dialog/DialogSuccess";

export default function Index() {
  const [openDialog, setOpenDialog] = React.useState(false);

  const [showPassword, setShowPassword] = React.useState(false);

  const handleClickShowPassword = () => {
    setShowPassword(!showPassword);
  };

  const handleMouseDownPassword = (event: { preventDefault: () => void }) => {
    event.preventDefault();
  };
  const handleClose = () => {
    setOpenDialog(false);
  };
  return (
    <>
      <Head>
        <title>Yaakz Member</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className="container2">
        <div className="bg-login" />
        <div className="regis-container">
          <div style={{ display: "flex", justifyContent: "center" }}>
            <Image src={mypic} width={200} height={200} alt="" />
          </div>
          <Typography style={{ textAlign: "center" }}>YAAKZ MEMBER</Typography>
          <Typography style={{ textAlign: "center", marginTop: 20 }}>
            เข้าสู่ระบบ
          </Typography>

          <div
            style={{
              display: "flex",
              justifyContent: "center",
              marginTop: 20,
            }}
          >
            <div className="input">
              <InputBase
                placeholder="อีเมล์"
                sx={{
                  marginLeft: 3,
                  marginTop: 0.5,
                  width: "100%",
                }}
                inputProps={{ "aria-label": "search" }}
              />
            </div>
          </div>

          <div
            style={{
              display: "flex",
              justifyContent: "space-evenly",
              marginTop: 20,
            }}
          >
            <div className="input">
              <InputBase
                placeholder="รหัสผ่าน"
                type={showPassword ? "text" : "password"}
                sx={{
                  width: "100%",
                  marginLeft: 3,
                }}
                endAdornment={
                  <InputAdornment position="end">
                    <IconButton
                      aria-label="toggle password visibility"
                      onClick={handleClickShowPassword}
                      onMouseDown={handleMouseDownPassword}
                    >
                      {showPassword ? <Visibility /> : <VisibilityOff />}
                    </IconButton>
                  </InputAdornment>
                }
              />
            </div>
          </div>

          <div
            style={{
              justifyContent: "center",
              display: "flex",
              marginTop: 20,
            }}
          >
            <Button href="home" className="btn-login" variant="contained">
              เข้าสู่ระบบ
            </Button>
          </div>
          <Divider
            style={{
              marginTop: 20,
            }}
          />
          <div
            style={{
              justifyContent: "center",
              display: "flex",
              marginTop: 20,
            }}
          >
            <Button href="register" className="btn-login" variant="contained">
              ลงทะเบียน
            </Button>
          </div>
        </div>

        <DialogProps
          open={openDialog}
          onClose={handleClose}
          text="เบอร์โทศัพท์นี้มีบัญชีผู้ใช้แล้วกรุณาใช้เบอร์โทรศัพท์อื่น"
          icon={
            <ErrorOutlineRounded
              style={{ width: 100, height: 100, color: "#5B5B5B" }}
            />
          }
        />
      </Box>
    </>
  );
}
