import QontoStepIcon from "@/components/Stapper";
import TapsProps from "@/components/Tabs";
import StatusDetailProps from "@/components/dialog/DialogStatusDetail";
import {
  AddRounded,
  ArrowBackIosNewRounded,
  CheckRounded,
  CloseRounded,
} from "@mui/icons-material";
import {
  Box,
  Tabs,
  Tab,
  Typography,
  Button,
  Divider,
  IconButton,
} from "@mui/material";
import Head from "next/head";
import router from "next/router";
import * as React from "react";

interface TabPanelProps {
  children?: React.ReactNode;
  index: number;
  value: number;
}

function CustomTabPanel(props: TabPanelProps) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <div style={{ padding: 10, display: "grid", justifyContent: "center" }}>
          {children}
        </div>
      )}
    </div>
  );
}

function CustomTabPanelStatus(props: TabPanelProps) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <div style={{ padding: 10, display: "grid", justifyContent: "center" }}>
          {children}
        </div>
      )}
    </div>
  );
}

function a11yProps(index: number) {
  return {
    id: `simple-tab-${index}`,
    "aria-controls": `simple-tabpanel-${index}`,
  };
}

function a11yPropsStatus(index: number) {
  return {
    id: `simple-tab-${index}`,
    "aria-controls": `simple-tabpanel-${index}`,
  };
}

export default function OrdeList() {
  const [value, setValue] = React.useState(0);
  const [valueStatus, setValueStatus] = React.useState(0);
  const [openDetail, setOpenDetail] = React.useState(false);
  const [openDetailStatusSuccess, setOpenDetailStatusSuccess] =
    React.useState(false);
  const [openDetailYaakShop, setOpenDetailYaakShop] = React.useState(false);
  const handleChange = (event: React.SyntheticEvent, newValue: number) => {
    setValue(newValue);
  };

  const handleClose = () => {
    setOpenDetail(false);
    setOpenDetailStatusSuccess(false);
    setOpenDetailYaakShop(false);
  };

  const handleChangestatus = (
    event: React.SyntheticEvent,
    newValue: number
  ) => {
    setValueStatus(newValue);
  };
  return (
    <>
      <Head>
        <title>Yaakz Member</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: "flex",
          justifyContent: "center",
          height: "70px",
          alignItems: "center",
        }}
      >
        <Typography style={{ fontSize: "24px" }}>การสั่งซื้อ</Typography>
      </div>
      <div className="box-order-list">
        <div
          style={{
            width: "100%",
            display: "flex",
            justifyContent: "center",
          }}
        >
          <div className="box-tabs">
            <Tabs
              value={value}
              onChange={handleChange}
              aria-label="basic tabs example"
            >
              <Tab label="Yaakz Shop" {...a11yProps(0)} />
              <Tab label="Yaakz Station" {...a11yProps(1)} />
              <Tab label="Pre-Order" {...a11yProps(2)} />
            </Tabs>
          </div>
        </div>
        <Divider style={{ color: "#5B5B5B", marginTop: 20 }} />

        <CustomTabPanel value={value} index={0}>
          <div
            className="box-item"
            onClick={(_) => setOpenDetailYaakShop(true)}
          >
            <div className="img-item">
              <Typography>รูปภาพ</Typography>
            </div>
            <div style={{ width: 230, marginTop: -5 }}>
              <Typography style={{ height: 55 }}>
                ยอดนักสืบจิ๋ว โคนัน ล.5 - วันสบายๆของซีโร่ (90)
              </Typography>
              <div style={{ display: "flex", justifyContent: "space-between" }}>
                <Typography style={{ fontSize: "14px" }}>
                  วันที่ซื้อ : 11/12/66
                </Typography>
                <Typography style={{ fontSize: "14px" }}>รวม 80 บาท</Typography>
              </div>
            </div>
          </div>
          <div className="box-item">
            <div className="img-item">
              <Typography>รูปภาพ</Typography>
            </div>
            <div style={{ width: 230, marginTop: -5 }}>
              <Typography style={{ height: 55 }}>
                ยอดนักสืบจิ๋ว โคนัน ล.5 - วันสบายๆของซีโร่ (90)
              </Typography>
              <div style={{ display: "flex", justifyContent: "space-between" }}>
                <Typography style={{ fontSize: "14px" }}>
                  วันที่ซื้อ : 11/12/66
                </Typography>
                <Typography style={{ fontSize: "14px" }}>รวม 80 บาท</Typography>
              </div>
            </div>
          </div>
        </CustomTabPanel>
        <CustomTabPanel value={value} index={1}>
          <Box
            sx={{
              borderBottom: 1,
              borderColor: "divider",
              display: "flex",
              justifyContent: "space-evenly",
              width: "100%",
            }}
          >
            <div className="box-tabs2">
              <Tabs
                value={valueStatus}
                onChange={handleChangestatus}
                aria-label="basic tabs example"
                style={{ width: "100%" }}
              >
                <Tab
                  style={{ width: "50%" }}
                  label="รอดำเนินการ"
                  {...a11yPropsStatus(0)}
                />
                <Tab
                  style={{ width: "50%" }}
                  label="สำเร็จ"
                  {...a11yPropsStatus(1)}
                />
              </Tabs>
            </div>
          </Box>
          <CustomTabPanelStatus value={valueStatus} index={0}>
            <div
              className="box-item-station"
              onClick={(_) => setOpenDetail(true)}
            >
              <div className="img-item">
                <Typography>รูปภาพ</Typography>
              </div>
              <div style={{ width: 230, marginTop: -5 }}>
                <Typography style={{ height: 55 }}>
                  ยอดนักสืบจิ๋ว โคนัน ล.5 - วันสบายๆของซีโร่ (90)
                </Typography>
                <Typography style={{ fontSize: "14px" }}>
                  เลขที่คำสั่งซื้อ
                </Typography>
                <div
                  style={{ display: "flex", justifyContent: "space-between" }}
                >
                  <Typography style={{ fontSize: "14px" }}>
                    วันที่ซื้อ : 11/12/66
                  </Typography>
                  <Typography style={{ fontSize: "14px" }}>
                    รวม 80 บาท
                  </Typography>
                </div>
                <QontoStepIcon step={1} />
              </div>
            </div>
          </CustomTabPanelStatus>
          <CustomTabPanelStatus value={valueStatus} index={1}>
            <div
              className="box-item-station"
              onClick={(_) => setOpenDetailStatusSuccess(true)}
            >
              <div className="img-item">
                <Typography>รูปภาพ</Typography>
              </div>
              <div style={{ width: 230, marginTop: -5 }}>
                <Typography style={{ height: 55 }}>
                  ยอดนักสืบจิ๋ว โคนัน ล.5 - วันสบายๆของซีโร่ (90)
                </Typography>
                <Typography style={{ fontSize: "14px" }}>
                  เลขที่คำสั่งซื้อ
                </Typography>
                <div
                  style={{ display: "flex", justifyContent: "space-between" }}
                >
                  <Typography style={{ fontSize: "14px" }}>
                    วันที่ซื้อ : 11/12/66
                  </Typography>
                  <Typography style={{ fontSize: "14px" }}>
                    รวม 80 บาท
                  </Typography>
                </div>
                <QontoStepIcon step={3} />
              </div>
            </div>
          </CustomTabPanelStatus>
        </CustomTabPanel>
        <CustomTabPanel value={value} index={2}>
          <Box
            sx={{
              borderBottom: 1,
              borderColor: "divider",
              display: "flex",
              justifyContent: "space-evenly",
              width: "100%",
            }}
          >
            <div className="box-tabs2">
              <Tabs
                value={valueStatus}
                onChange={handleChangestatus}
                aria-label="basic tabs example"
                style={{ width: "100%" }}
              >
                <Tab
                  style={{ width: "50%" }}
                  label="รอดำเนินการ"
                  {...a11yPropsStatus(0)}
                />
                <Tab
                  style={{ width: "50%" }}
                  label="สำเร็จ"
                  {...a11yPropsStatus(1)}
                />
              </Tabs>
            </div>
          </Box>
          <CustomTabPanelStatus value={valueStatus} index={0}>
            <div
              className="box-item-station"
              onClick={(_) => setOpenDetail(true)}
            >
              <div className="img-item">
                <Typography>รูปภาพ</Typography>
              </div>
              <div style={{ width: 230, marginTop: -5 }}>
                <Typography style={{ height: 55 }}>
                  ยอดนักสืบจิ๋ว โคนัน ล.5 - วันสบายๆของซีโร่ (90)
                </Typography>
                <Typography style={{ fontSize: "14px" }}>
                  เลขที่คำสั่งซื้อ
                </Typography>
                <div
                  style={{ display: "flex", justifyContent: "space-between" }}
                >
                  <Typography style={{ fontSize: "14px" }}>
                    วันที่ซื้อ : 11/12/66
                  </Typography>
                  <Typography style={{ fontSize: "14px" }}>
                    รวม 80 บาท
                  </Typography>
                </div>
                <QontoStepIcon step={1} />
              </div>
            </div>
          </CustomTabPanelStatus>
          <CustomTabPanelStatus value={valueStatus} index={1}>
            <div
              className="box-item-station"
              onClick={(_) => setOpenDetailStatusSuccess(true)}
            >
              <div className="img-item">
                <Typography>รูปภาพ</Typography>
              </div>
              <div style={{ width: 230, marginTop: -5 }}>
                <Typography style={{ height: 55 }}>
                  ยอดนักสืบจิ๋ว โคนัน ล.5 - วันสบายๆของซีโร่ (90)
                </Typography>
                <Typography style={{ fontSize: "14px" }}>
                  เลขที่คำสั่งซื้อ
                </Typography>
                <div
                  style={{ display: "flex", justifyContent: "space-between" }}
                >
                  <Typography style={{ fontSize: "14px" }}>
                    วันที่ซื้อ : 11/12/66
                  </Typography>
                  <Typography style={{ fontSize: "14px" }}>
                    รวม 80 บาท
                  </Typography>
                </div>
                <QontoStepIcon step={3} />
              </div>
            </div>
          </CustomTabPanelStatus>
        </CustomTabPanel>
      </div>

      <StatusDetailProps
        text=""
        onClose={handleClose}
        open={openDetail}
        step={1}
      />
      <StatusDetailProps
        text=""
        onClose={handleClose}
        open={openDetailStatusSuccess}
        step={3}
      />
      <StatusDetailProps
        text="YaakzShop"
        onClose={handleClose}
        open={openDetailYaakShop}
        step={3}
      />

      <TapsProps />
    </>
  );
}
