import Head from "next/head";
import * as React from "react";

import {
  Box,
  Button,
  Card,
  CardContent,
  CardMedia,
  IconButton,
  Typography,
} from "@mui/material";
import { AddRounded, ArrowBackIosNewRounded } from "@mui/icons-material";

import TapsProps from "@/components/Tabs";
import router from "next/router";
import Image from "next/image";
import mypic from "../assets/imges/1709677279796.jpg";

export default function ProductDetail() {
  return (
    <>
      <Head>
        <title>Yaakz Member</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className="container">
        <div className="toolbar">
          <IconButton onClick={() => router.back()}>
            <ArrowBackIosNewRounded />
          </IconButton>
          <Typography style={{ fontSize: "24px" }}>รายละเอียดสินค้า</Typography>
          <div />
        </div>
        <div className="box-image-product-detail">
          <div className="box-image-product">
            <Card
              sx={{
                boxShadow: "none",
                display: "grid",
                justifyContent: "center",
              }}
            >
              <CardMedia className="img-detail-reward">
                <Image
                  src={mypic}
                  alt=""
                  style={{
                    width: "100%",
                    height: "100%",
                    objectFit: "cover",
                    position: "absolute",
                  }}
                />
              </CardMedia>
            </Card>
          </div>
        </div>
        <div className="product-detail-container">
          <div>
            <Typography
              style={{ textAlign: "center", fontSize: "20px", padding: 20 }}
            >
              ยอดนักสืบจิ๋ว โคนัน ล.8 - วันสบายๆ ของซีโร่ (90)
            </Typography>
            <div className="text-product-detail-container">
              <div className="text-product-detail-left">
                <Typography>เล่มที่&nbsp;&nbsp;:</Typography>
                <Typography>ราคาปก&nbsp;&nbsp;:</Typography>
                <Typography>Barcode&nbsp;&nbsp;:</Typography>
                <Typography>สำนักพิมพ์&nbsp;&nbsp;:</Typography>
                <Typography>วันที่วางจำหน่าย&nbsp;&nbsp;:</Typography>
              </div>
              <div>
                <Typography>90</Typography>
                <Typography>90 บาท</Typography>
                <Typography>9786165971171</Typography>
                <Typography>No Information</Typography>
                <Typography>12/12/66</Typography>
              </div>
            </div>
          </div>
          <div className="bottom-btn-add">
            <Button color="info" className="btn-regis" variant="contained">
              ดำเนินการต่อ
            </Button>
          </div>
        </div>
      </Box>
    </>
  );
}
